### ISSUE TITLE
Project Tracking Board

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/infrastructure#7]
## Track ALL the Issues
Looking at waffle.io. It looks very promising. I played around with the multi-repo linking which isn't perfect but it works. ~~I'm currently waiting upon the creation of ipfs/ipfs to act as a root repo for the IPFS projects.~~
Tasks for https://waffle.io/ipfs/ipfs:
- [x] Get me permissions to ipfs/ipfs
- [x] Link other repos to ipfs/ipfs
- [x] Correctly set up columns

**Comment by jbenet** [comment]
You should have access to `ipfs/ipfs` now

**Comment by jbenet** [comment]
Would be good to have a doc (either in this repo, in ipfs/community or ipfs/ipfs) describing how this board works (with links to kanban boards in general for those unfamiliar). Will be important to include a description of each column and how they differ. may be able to just lift it straight from https://www.zenhub.io/blog/how-the-zenhub-team-uses-zenhub-boards-on-github/#zenhubboardsforproductdevelopment

**Comment by dylanPowers** [comment]
I feel this repo will be most suitable for that sort of documentation. It's infrastructure related, so might as well document it in the same place.

**Comment by jbenet** [comment]
gtm

**Comment by dylanPowers** [comment]
Would we have any reason not to include one of the ipfs org repos on this board? I want to make sure before I go crazy linking stuff to it.

**Comment by jbenet** [comment]
Thanks for asking! Nope, go ahead.



—

**Comment by dylanPowers** [comment]
Okay I've got all the repos from the ipfs org added. I'm calling this complete

**Comment by jbenet** [comment]
Hey @dylanPowers i still need to move some repos. I'll post them here when i do + reopen

**Comment by dylanPowers** [comment]
@jbenet Sounds good to me
